version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3344:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --sql-mode=""
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 100M  # Optional: Set upload limit for file imports
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    name: mysql-network
